services:
  - type: web
    name: svai-assist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: META_TOKEN
        sync: false
      - key: META_PHONE_ID
        sync: false
      - key: VERIFY_TOKEN
        value: false
