services:
  - type: web
    name: svai-assist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: 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
      - key: META_TOKEN
        sync: EAAMdWe4twaYBQ3U4tS93P5bKKcaIl64fin7rHm2yeIQohWjsuy1XvlS6JGHTCvkIOpJshEz2MimdLYyRzRlhh2APPvQYGUXZBATSyRy3ioXfAL1ZCZAyDA4i0w8EGFBq3fkeKrsZBDhheXP2ZClReIObpDkaPxaI18JLZCu9xV186uihRuCMmzim2NK75e10S8XgKev4zLkN0bZAbp5BwlXIVkFvST4vKDqwArJ
      - key: META_PHONE_ID
        sync: 961239650414311
      - key: VERIFY_TOKEN
        value: vinay123
